services:
  traefik:
    image: traefik:v3.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./backend/docker/development/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - nextgen_local_network
    command:
      - --providers.docker
  
  api: &api
    build:
      context: .
      dockerfile: ./backend/docker/development/fastapi/Dockerfile
    volumes:
      - .:/src
      - ./backend/app/logs:/src/backend/app/logs
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.env.development
    depends_on:
      - postgres
      - mailpit
    command: /start.sh
    networks:
      - nextgen_local_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api.service=api-service"
      - "traefik.http.services.api-service.loadbalancer.server.port=8000"

  mailpit:
    image: axllent/mailpit:v1.20.3
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - nextgen_mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - nextgen_local_network

  postgres:
    build:
      context: .
      dockerfile: ./backend/docker/development/postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - nextgen_local_db:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.development
    networks:
      - nextgen_local_network

networks:
  nextgen_local_network:
    external: true

volumes:
  nextgen_local_db:
  nextgen_mailpit_data:
