services:
  postgres:
    build:
      context: .
      dockerfile: ./backend/Docker/development/postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - nextgen_local_db:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.development
    networks:
      - nextgen_local_network

networks:
  nextgen_local_network:
    external: true

volumes:
  nextgen_local_db:

    