"""add_user_preferred_language

Revision ID: 0723cbc5d2ba
Revises: 49a875651ae0
Create Date: 2026-02-17 22:33:14.353248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0723cbc5d2ba'
down_revision: Union[str, None] = '49a875651ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('preferred_language', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'preferred_language')
    # ### end Alembic commands ###
